services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 1s
      timeout: 3s
      retries: 5
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
  backend:
    build: ./backend/
    environment:
      - GIN_MODE=release
      - PORT=80
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=localdb
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost/ping | grep pong
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend/
    environment:
      - API_URL=http://backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASS=
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 80:3000

volumes:
  postgres-data:
  redis-data:
  minio-data:
